# Generated by Django 3.0 on 2020-09-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_like_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_one', models.CharField(max_length=50)),
                ('option_two', models.CharField(max_length=50)),
                ('option_three', models.CharField(max_length=50)),
                ('option_four', models.CharField(max_length=50)),
                ('option_one_count', models.IntegerField(default=0)),
                ('option_two_count', models.IntegerField(default=0)),
                ('option_three_count', models.IntegerField(default=0)),
                ('option_four_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
